all:
	@echo "-------------------------------------------"
	@echo "compile app" 
	gcc -c -g taskInterface.c -o $(ARTIFACTS_DIR)/taskInterface.o
	gcc -c -g taskInstance.c -o $(ARTIFACTS_DIR)/taskInstance.o